{
    "apiUrl": "URL DEL SERVIDOR",
    "protocol": "PROTOCOLO A USAR HTTP o HTTPS",
    "isProdMode": false,
    "versionUrl": "URL DEL VERSIONAMIENTO DE APP",
    "CFAccessClientId": "SECRET CLIENT ID DE CLOUDFLARE",
    "CFAccessClientSecret": "SECRET KEY DE CLOUDFLARE",
    "CFAccessSiteKey": "SITE KEY DE CLOUDFLARE",
    "GOOGLE_SHEET_ERROR_LOG_URL": "URL DE GOOGLE SHEET DE ERRORES",
    "GOOGLE_SHEET_BITACORA_LOG_URL": "URL DE GOOGLE SHEET DE BITACORA",
    "GOOGLE_PLACES_API": "API KEY DE GOOGLE PLACES",
    "REPORTE_SERVICE_URL": "URL DEL REPORTE SERVICE",
    "REPORTE_SERVICE_API_KEY": "API KEY DEL REPORTE SERVICE"
}