import 'package:bloc/bloc.dart';
import 'package:core_financiero_app/src/config/local_storage/local_storage.dart';
import 'package:core_financiero_app/src/datasource/solicitudes/hn/solicitudes/asalariado/solicitud_asalariado_hn.dart';
import 'package:core_financiero_app/src/datasource/solicitudes/hn/solicitudes/nuevamenor/solicitud_nueva_menor_hn.dart';
import 'package:core_financiero_app/src/datasource/solicitudes/ni/historial_crediticio/historial_crediticio.dart';
import 'package:core_financiero_app/src/domain/exceptions/app_exception.dart';
import 'package:core_financiero_app/src/domain/repository/solicitudes_credito/hn/solicitudes_credito_hn_repository.dart';
import 'package:core_financiero_app/src/presentation/bloc/auth/branch_team/branchteam_cubit.dart';
import 'package:core_financiero_app/src/presentation/screens/solicitudes/ni/crear_solicitud_screen.dart';
import 'package:equatable/equatable.dart';

part 'update_solicitud_nueva_menor_state.dart';

class UpdateSolicitudNuevaMenorCubit
    extends Cubit<UpdateSolicitudNuevaMenorState> {
  final SolicitudesCreditoHnRepository _repository;
  UpdateSolicitudNuevaMenorCubit(this._repository)
      : super(UpdateSolicitudNuevaMenorInitial());

  Future<void> getSolicitudDataById({
    required String tipoSolicitud,
    required int idSolicitud,
  }) async {
    emit(state.copyWith(status: Status.inProgress));
    try {
      final resp = await _repository.getSolicitudDataById(
        tipoSolicitud: tipoSolicitud,
        idSolicitud: idSolicitud,
      );
      emit(
        state.copyWith(
          status: Status.done,
          id: resp.data.id,
          origenSolicitudCodigo: resp.data.origenSolicitudCodigo,
          origenSolicitudNombre: resp.data.origenSolicitudNombre,
          nombre1: resp.data.nombre1,
          nombre2: resp.data.nombre2,
          apellido1: resp.data.apellido1,
          apellido2: resp.data.apellido2,
          cedula: resp.data.cedula,
          paisEmisorCedulaCodigo: resp.data.paisEmisorCedulaCodigo,
          paisEmisorCedulaNombre: resp.data.paisEmisorCedulaNombre,
          tipoDocumentoCodigo: resp.data.tipoDocumentoCodigo,
          tipoDocumentoNombre: resp.data.tipoDocumentoNombre,
          tipoDocumentoConyugeCodigo: resp.data.tipoDocumentoConyugeCodigo,
          tipoDocumentoConyugeNombre: resp.data.tipoDocumentoConyugeNombre,
          nombrePublico: resp.data.nombrePublico,
          fechaEmisionCedula:
              resp.data.fechaEmisionCedula?.toUtc().toIso8601String(),
          fechaVencimientoCedula:
              resp.data.fechaVencimientoCedula?.toUtc().toIso8601String(),
          fechaNacimiento: resp.data.fechaNacimiento?.toUtc().toIso8601String(),
          telefono: resp.data.telefono,
          celular: resp.data.celular,
          direccionCasa: resp.data.direccionCasa,
          barrioCasa: resp.data.barrioCasa,
          municipioCasaCodigo: resp.data.municipioCasaCodigo,
          municipioCasaNombre: resp.data.municipioCasaNombre,
          departamentoCasaCodigo: resp.data.departamentoCasaCodigo,
          departamentoCasaNombre: resp.data.departamentoCasaNombre,
          paisCasaCodigo: resp.data.paisCasaCodigo,
          paisCasaNombre: resp.data.paisCasaNombre,
          nacionalidad: resp.data.nacionalidad,
          condicionCasaCodigo: resp.data.condicionCasaCodigo,
          condicionCasaNombre: resp.data.condicionCasaNombre,
          anosResidirCasa: resp.data.anosResidirCasa,
          email: resp.data.email,
          monto: resp.data.monto,
          monedaCodigo: resp.data.monedaCodigo,
          monedaNombre: resp.data.monedaNombre,
          propositoCodigo: resp.data.propositoCodigo,
          propositoNombre: resp.data.propositoNombre,
          descripcionDestino: resp.data.descripcionDestino,
          frecuenciaCodigo: resp.data.frecuenciaCodigo,
          frecuenciaNombre: resp.data.frecuenciaNombre,
          cuota: resp.data.cuota,
          sectorCodigo: resp.data.sectorCodigo,
          sectorNombre: resp.data.sectorNombre,
          personasACargo: resp.data.personasACargo,
          estadoCivilCodigo: resp.data.estadoCivilCodigo,
          estadoCivilNombre: resp.data.estadoCivilNombre,
          nombreConyugue: resp.data.nombreConyugue,
          trabajaConyugue: resp.data.trabajaConyugue,
          trabajoConyugue: resp.data.trabajoConyugue,
          direccionTrabajoConyugue: resp.data.direccionTrabajoConyugue,
          telefonoTrabajoConyugue: resp.data.telefonoTrabajoConyugue,
          productoCodigo: resp.data.productoCodigo,
          productoNombre: resp.data.productoNombre,
          observacion: resp.data.observacion,
          ubicacionLongitud: resp.data.ubicacionLongitud,
          ubicacionLatitud: resp.data.ubicacionLatitud,
          escolaridadCodigo: resp.data.escolaridadCodigo,
          escolaridadNombre: resp.data.escolaridadNombre,
          cantidadHijos: resp.data.cantidadHijos,
          sexoCodigo: resp.data.sexoCodigo,
          sexoNombre: resp.data.sexoNombre,
          paisNacimientoCodigo: resp.data.paisNacimientoCodigo,
          paisNacimientoNombre: resp.data.paisNacimientoNombre,
          nacionalidadConyugue: resp.data.nacionalidadConyugue,
          ubicacion: resp.data.ubicacion,
          esPeps: resp.data.esPeps,
          nombreDeEntidadPeps: resp.data.nombreDeEntidadPeps,
          paisPeps: resp.data.paisPeps,
          periodoPeps: resp.data.periodoPeps,
          cargoOficialPeps: resp.data.cargoOficialPeps,
          tieneFamiliarPeps: resp.data.tieneFamiliarPeps,
          nombreFamiliarPeps2: resp.data.nombreFamiliarPeps2,
          parentescoFamiliarPeps2Codigo:
              resp.data.parentescoFamiliarPeps2Codigo,
          parentescoFamiliarPeps2Nombre:
              resp.data.parentescoFamiliarPeps2Nombre,
          cargoFamiliarPeps2: resp.data.cargoFamiliarPeps2,
          nombreEntidadPeps2: resp.data.nombreEntidadPeps2,
          periodoPeps2: resp.data.periodoPeps2,
          paisPeps2: resp.data.paisPeps2,
          actividadPredominanteCodigo: resp.data.actividadPredominanteCodigo,
          actividadPredominanteNombre: resp.data.actividadPredominanteNombre,
          esFamiliarEmpleado: resp.data.esFamiliarEmpleado,
          nombreFamiliar: resp.data.nombreFamiliar,
          cedulaFamiliar: resp.data.cedulaFamiliar,
          tipoPersonaCodigo: resp.data.tipoPersonaCodigo,
          tipoPersonaNombre: resp.data.tipoPersonaNombre,
          plazoSolicitud: resp.data.plazoSolicitud,
          fechaPrimerPagoSolicitud:
              resp.data.fechaPrimerPagoSolicitud?.toUtc().toIso8601String(),
          rtn: resp.data.rtn,
          codigoUsa: resp.data.codigoUsa,
          tipoClienteCodigo: resp.data.tipoClienteCodigo,
          tipoClienteNombre: resp.data.tipoClienteNombre,
          actividadEconomicaCiuu1Codigo:
              resp.data.actividadEconomicaCiuu1Codigo,
          actividadEconomicaCiuu1Nombre:
              resp.data.actividadEconomicaCiuu1Nombre,
          actividadEconomicaCiuu2Codigo:
              resp.data.actividadEconomicaCiuu2Codigo,
          actividadEconomicaCiuu2Nombre:
              resp.data.actividadEconomicaCiuu2Nombre,
          actividadEconomicaCiuu3Codigo:
              resp.data.actividadEconomicaCiuu3Codigo,
          actividadEconomicaCiuu3Nombre:
              resp.data.actividadEconomicaCiuu3Nombre,
          ocupacionCodigo: resp.data.ocupacionCodigo,
          ocupacionNombre: resp.data.ocupacionNombre,
          profesionCodigo: resp.data.profesionCodigo,
          profesionNombre: resp.data.profesionNombre,
          actividadEconomicaDescripcion1:
              resp.data.actividadEconomicaDescripcion1,
          actividadEconomicaDescripcion2:
              resp.data.actividadEconomicaDescripcion2,
          actividadEconomicaDescripcion3:
              resp.data.actividadEconomicaDescripcion3,
          ejerceApnfd: resp.data.ejerceApnfd,
          esApnfd: resp.data.esApnfd,
          paisDestinoCodigo: resp.data.paisDestinoCodigo,
          paisDestinoNombre: resp.data.paisDestinoNombre,
          departamentoDestinoCodigo: resp.data.departamentoDestinoCodigo,
          departamentoDestinoNombre: resp.data.departamentoDestinoNombre,
          municipioDestinoCodigo: resp.data.municipioDestinoCodigo,
          municipioDestinoNombre: resp.data.municipioDestinoNombre,
          aldeaDestinoCodigo: resp.data.aldeaDestinoCodigo,
          aldeaDestinoNombre: resp.data.aldeaDestinoNombre,
          caserioDestino: resp.data.caserioDestino,
          barrioDestino: resp.data.barrioDestino,
          caserioCasa: resp.data.caserioCasa,
          aldeaCodigo: resp.data.aldeaCodigo,
          aldeaNombre: resp.data.aldeaNombre,
          nombreNegocio: resp.data.nombreNegocio,
          direccionNegocio: resp.data.direccionNegocio,
          barrioNegocio: resp.data.barrioNegocio,
          caserioNegocio: resp.data.caserioNegocio,
          paisNegocioCodigo: resp.data.paisNegocioCodigo,
          paisNegocioNombre: resp.data.paisNegocioNombre,
          departamentoNegocioCodigo: resp.data.departamentoNegocioCodigo,
          departamentoNegocioNombre: resp.data.departamentoNegocioNombre,
          municipioNegocioCodigo: resp.data.municipioNegocioCodigo,
          municipioNegocioNombre: resp.data.municipioNegocioNombre,
          aldeaNegocioCodigo: resp.data.aldeaNegocioCodigo,
          aldeaNegocioNombre: resp.data.aldeaNegocioNombre,
          condicionNegocioCodigo: resp.data.condicionNegocioCodigo,
          condicionNegocioNombre: resp.data.condicionNegocioNombre,
          telefonoNegocio: resp.data.telefonoNegocio,
          celularNegocio: resp.data.celularNegocio,
          tiempoFuncionamientoNegocio: resp.data.tiempoFuncionamientoNegocio,
          puestoNegocio: resp.data.puestoNegocio,
          horarioTrabajo: resp.data.horarioTrabajo,
          experiencia: resp.data.experiencia,
          horarioVisita: resp.data.horarioVisita,
          ingresosNetos: resp.data.ingresosNetos,
          grupoCicloId: resp.data.grupoCicloId,
          cicloEstadoNombre: resp.data.cicloEstadoNombre,
          cicloEstadoCodigo: resp.data.cicloEstadoCodigo,
          grupoNombre: resp.data.grupoNombre,
          grupoCodigo: resp.data.grupoCodigo,
          apellido3: resp.data.apellido3,
          nacionalidad2Codigo: resp.data.nacionalidad2Codigo,
          nacionalidad3Codigo: resp.data.nacionalidad3Codigo,
          nacionalidad2Nombre: resp.data.nacionalidad2Nombre,
          nacionalidad3Nombre: resp.data.nacionalidad3Nombre,
          tipoPersonaCNBSCodigo: resp.data.tipoPersonaCNBSCodigo,
          tipoPersonaCNBSNombre: resp.data.tipoPersonaCNBSNombre,
          cargoGrupoCodigo: resp.data.cargoGrupoCodigo,
          cargoGrupoNombre: resp.data.cargoGrupoNombre,
          nombre3: resp.data.nombre3,
          actividadDescripcionConyuge: resp.data.actividadDescripcionConyuge,
          documentoConyuge: resp.data.documentoConyuge,
          barrioTrabajo: resp.data.barrioTrabajo,
          telefonoTrabajo: resp.data.telefonoTrabajo,
          tiempoLaboral: resp.data.tiempoLaboral,
          lugarTrabajoAnterior: resp.data.lugarTrabajoAnterior,
          salarioNetoCordoba: resp.data.salarioNetoCordoba,
          totalIngresoMes: resp.data.totalIngresoMes,
          cargo: resp.data.cargo,
          direccionTrabajo: resp.data.direccionTrabajo,
          fuenteOtrosIngresos: resp.data.fuenteOtrosIngresos,
          nombreTrabajo: resp.data.nombreTrabajo,
          otrosIngresosCordoba: resp.data.otrosIngresosCordoba,
          profesionConyugue: resp.data.profesionConyugue,
          tiempoLaborarConyugue: resp.data.tiempoLaborarConyugue,
          sueldoMesConyugue: resp.data.sueldoMesConyugue,
          otrosIngresosConyugue: resp.data.otrosIngresosConyugue,
          nombreFamiliarCercano: resp.data.nombreFamiliarCercano,
          direccionFamiliarCercano: resp.data.direccionFamiliarCercano,
          telefonoFamiliarCercano: resp.data.telefonoFamiliarCercano,
          fuenteOtrosIngresosConyugue: resp.data.fuenteOtrosIngresosConyugue,

          // historialCredito:  resp.data.hi.,
        ),
      );
    } on AppException catch (e) {
      emit(state.copyWith(
        status: Status.error,
        errorMsg: e.optionalMsg,
      ));
    } catch (e) {
      emit(state.copyWith(
        status: Status.error,
        errorMsg: e.toString(),
      ));
    }
  }

  void onFieldChanged(UpdateSolicitudNuevaMenorState Function() copyWithFn) {
    emit(copyWithFn());
  }

  updateSolicitud({
    required TypeForm tipoSolicitud,
    required int idSolicitud,
  }) {
    return switch (tipoSolicitud) {
      TypeForm.nueva => updateSolicitudNuevaMenor(
          idSolicitud: idSolicitud,
        ),
      TypeForm.asalariado => updateSolicitudAsalariado(
          idSolicitud: idSolicitud,
        ),
      _ => throw Exception('Tipo Solicitud no reconocido: $tipoSolicitud'),
    };
  }

  Future<void> updateSolicitudAsalariado({
    required int idSolicitud,
  }) async {
    emit(state.copyWith(updateStatus: Status.inProgress));
    try {
      await _repository.updateSolicitudAsalariado(
        idSolicitud: idSolicitud,
        solicitudAsalariado: SolicitudAsalariadoHn(
          database: LocalStorage().database,
          isOffline: false,
          origenSolicitudCodigo: state.origenSolicitudCodigo,
          nombre1: state.nombre1,
          nombre2: state.nombre2,
          apellido1: state.apellido1,
          apellido2: state.apellido2,
          cedula: state.cedula,
          paisEmisorCedulaCodigo: state.paisEmisorCedulaCodigo,
          fechaVencimientoCedula:
              DateTime.tryParse(state.fechaVencimientoCedula)!,
          telefono: state.telefono,
          celular: state.celular,
          direccionCasa: state.direccionCasa,
          barrioCasa: state.barrioCasa,
          municipioCasaCodigo: state.municipioCasaCodigo,
          departamentoCasaCodigo: state.departamentoCasaCodigo,
          paisCasaCodigo: state.paisCasaCodigo,
          nacinalidad: state.nacionalidad,
          condicionCasaCodigo: state.condicionCasaCodigo,
          anosResidirCasa: state.anosResidirCasa,
          email: state.email,
          monto: state.monto,
          monedaCodigo: state.monedaCodigo,
          propositoCodigo: state.propositoCodigo,
          frecuenciaCodigo: state.frecuenciaCodigo,
          cuota: state.cuota.toDouble(),
          sectorCodigo: state.sectorCodigo,
          personasACargo: state.personasACargo,
          estadoCivilCodigo: state.estadoCivilCodigo,
          nombreConyugue: state.nombreConyugue,
          trabajaConyugue: state.trabajaConyugue,
          trabajoConyugue: state.trabajoConyugue,
          direccionTrabajoConyugue: state.direccionTrabajoConyugue,
          telefonoTrabajoConyugue: state.telefonoTrabajoConyugue,
          productoCodigo: state.productoCodigo,
          observacion: state.observacion,
          ubicacionLongitud: state.ubicacionLongitud,
          ubicacionLatitud: state.ubicacionLatitud,
          escolaridadCodigo: state.escolaridadCodigo,
          cantidadHijos: state.cantidadHijos,
          nombrePublico: state.nombrePublico,
          sexoCodigo: state.sexoCodigo,
          paisNacimientoCodigo: state.paisNacimientoCodigo,
          nacionalidadConyugue: state.nacionalidadConyugue,
          ubicacion: state.ubicacion,
          espeps: state.esPeps,
          nombreDeEntidadPeps: state.nombreDeEntidadPeps,
          paisPeps: state.paisPeps,
          periodoPeps: state.periodoPeps,
          cargoOficialPeps: state.cargoOficialPeps,
          tieneFamiliarPeps: state.tieneFamiliarPeps,
          nombreFamiliarPeps2: state.nombreFamiliarPeps2,
          parentescoFamiliarPeps2: state.parentescoFamiliarPeps2Codigo,
          cargoFamiliarPeps2: state.cargoFamiliarPeps2,
          nombreEntidadPeps2: state.nombreEntidadPeps2,
          periodoPeps2: state.periodoPeps2,
          paisPeps2: state.paisPeps2,
          actividadPredominanteCodigo: state.actividadPredominanteCodigo,
          esFamiliarEmpleado: state.esFamiliarEmpleado,
          nombreFamiliar: state.nombreFamiliar,
          cedulaFamiliar: state.cedulaFamiliar,
          tipoDocumentoCodigo: state.tipoDocumentoCodigo,
          tipoPersonaCodigo: state.tipoPersonaCodigo,
          plazoSolicitud: state.plazoSolicitud,
          fechaPrimerPagoSolicitud:
              DateTime.tryParse(state.fechaPrimerPagoSolicitud)!,
          nombreTrabajo: state.nombreTrabajo,
          direccionTrabajo: state.direccionTrabajo,
          barrioTrabajo: state.barrioTrabajo,
          cargo: state.cargo,
          direccionFamiliarCercano: state.direccionFamiliarCercano,
          fuenteOtrosIngresos: state.fuenteOtrosIngresos,
          fuenteOtrosIngresosConyugue: state.fuenteOtrosIngresosConyugue,
          lugarTrabajoAnterior: state.lugarTrabajoAnterior,
          nombreFamiliarCercano: state.nombreFamiliarCercano,
          parentescoFamiliarCercanoCodigo: '',
          otrosIngresosConyugue: state.otrosIngresosConyugue,
          otrosIngresosCordoba: state.otrosIngresosCordoba,
          profesionConyugue: state.profesionConyugue,
          salarioNetoCordoba: state.salarioNetoCordoba,
          sueldoMesConyugue: state.sueldoMesConyugue,
          telefonoFamiliarCercano: state.telefonoFamiliarCercano,
          telefonoTrabajo: state.telefonoTrabajo,
          tiempoLaborar: state.tiempoLaboral,
          tiempoLaborarConyugue: state.tiempoLaborarConyugue,
          totalIngresoMes: state.totalIngresoMes,
          totalIngresoMesConyugue:
              state.otrosIngresosConyugue + state.sueldoMesConyugue,
          rtn: state.rtn,
          codigoUsa: state.codigoUsa,
          tipoPersonaCnbsidCodigo: state.tipoPersonaCNBSCodigo,
          estatusClienteCodigo: '',
          tipoClienteCodigo: state.tipoClienteCodigo,
          actividadEconomicaCiuu1Codigo: state.actividadEconomicaCiuu1Codigo,
          actividadEconomicaCiuu2Codigo: state.actividadEconomicaCiuu2Codigo,
          actividadEconomicaCiuu3Codigo: state.actividadEconomicaCiuu3Codigo,
          nivelAproximadoDeIngresosCodigo: '',
          ocupacionCodigo: state.ocupacionCodigo,
          profesionCodigo: state.profesionCodigo,
          actividadEconomicaDescripcion1: state.actividadEconomicaDescripcion1,
          actividadEconomicaDescripcion2: state.actividadEconomicaDescripcion2,
          actividadEconomicaDescripcion3: state.actividadEconomicaDescripcion3,
          ejerceApnfd: state.ejerceApnfd,
          esApnfd: state.esApnfd,
          paisDestinoCodigo: state.paisDestinoCodigo,
          departamentoDestinoCodigo: state.departamentoDestinoCodigo,
          municipioDestinoId: state.municipioDestinoCodigo,
          aldeaDestinoCodigo: state.aldeaDestinoCodigo,
          caserioDestino: state.caserioDestino,
          barrioDestino: state.barrioDestino,
          caseriCasa: state.caserioCasa,
          aldeaCodigo: state.aldeaCodigo,
          descripcionDestino: state.descripcionDestino,
          tipoDocumentoConyugeCodigo: state.tipoDocumentoConyugeCodigo,
          cedulaConyuge: state.documentoConyuge,
          historialCredito: state.historialCredito,
          fechaNacimiento: DateTime.tryParse(state.fechaNacimiento),
          fechaEmisionCedula: DateTime.tryParse(state.fechaEmisionCedula),
        ),
      );
      emit(state.copyWith(updateStatus: Status.done));
    } on AppException catch (e) {
      emit(state.copyWith(updateStatus: Status.error, errorMsg: e.optionalMsg));
    } catch (e) {
      emit(state.copyWith(updateStatus: Status.error, errorMsg: e.toString()));
    }
  }

  Future<void> updateSolicitudNuevaMenor({
    required int idSolicitud,
  }) async {
    emit(state.copyWith(updateStatus: Status.inProgress));
    try {
      await _repository.updateSolicitudNuevaMenor(
        idSolicitud: idSolicitud,
        solicitudNuevaMenor: SolicitudNuevaMenorHn(
          actividadDescripcionConyugue: state.actividadDescripcionConyuge,
          documentoConyuge: state.documentoConyuge,
          actividadEconomicaCnbs3Codigo: state.actividadEconomicaCiuu3Codigo,
          database: LocalStorage().database,
          origenSolicitudCodigo: state.origenSolicitudCodigo,
          nombre1: state.nombre1,
          apellido1: state.apellido1,
          cedula: state.cedula,
          paisEmisorCedulaCodigo: state.paisEmisorCedulaCodigo,
          fechaVencimientoCedula:
              DateTime.tryParse(state.fechaVencimientoCedula)!,
          fechaNacimiento: DateTime.parse(state.fechaNacimiento),
          telefono: state.telefono,
          celular: state.celular,
          direccionCasa: state.direccionCasa,
          barrioCasa: state.barrioCasa,
          municipioCasaCodigo: state.municipioCasaCodigo,
          departamentoCasaCodigo: state.departamentoCasaCodigo,
          paisCasaCodigo: state.paisCasaCodigo,
          profesion: state.profesionCodigo,
          ocupacion: state.ocupacionCodigo,
          condicionCasaCodigo: state.condicionCasaCodigo,
          anosResidirCasa: state.anosResidirCasa,
          monto: state.monto,
          monedaCodigo: state.monedaCodigo,
          propositoCodigo: state.propositoCodigo,
          frecuenciaCodigo: state.frecuenciaCodigo,
          cuota: state.cuota.toDouble(),
          sectorCodigo: state.sectorCodigo,
          nombreNegocio: state.nombreNegocio,
          tiempoFuncionamientoNegocio: state.tiempoFuncionamientoNegocio,
          direccionNegocio: state.direccionNegocio,
          barrioNegocio: state.barrioNegocio,
          municipioNegocioCodigo: state.municipioNegocioCodigo,
          condicionNegocioCodigo: state.condicionNegocioCodigo,
          horarioTrabajo: state.horarioTrabajo,
          horarioVisita: state.horarioVisita,
          personasACargo: state.personasACargo,
          estadoCivilCodigo: state.estadoCivilCodigo,
          nombreConyugue: state.nombreConyugue,
          trabajaConyugue: state.trabajaConyugue,
          trabajoConyugue: state.trabajoConyugue,
          direccionTrabajoConyugue: state.direccionTrabajoConyugue,
          telefonoTrabajoConyugue: state.telefonoTrabajoConyugue,
          productoCodigo: state.productoCodigo,
          observacion: state.observacion,
          sucursal: '',
          ubicacionLongitud: state.ubicacionLongitud,
          ubicacionLatitud: state.ubicacionLatitud,
          escolaridadCodigo: state.escolaridadCodigo,
          cantidadHijos: state.cantidadHijos,
          nombrePublico: state.nombrePublico,
          sexoCodigo: state.sexoCodigo,
          paisNacimientoCodigo: state.paisNacimientoCodigo,
          nacionalidadConyugue: state.nacionalidadConyugue,
          ubicacion: state.ubicacion,
          espeps: state.esPeps,
          nombreDeEntidadPeps: state.nombreDeEntidadPeps,
          paisPeps: state.paisPeps,
          periodoPeps: state.periodoPeps,
          cargoOficialPeps: state.cargoOficialPeps,
          tieneFamiliarPeps: state.tieneFamiliarPeps,
          nombreFamiliarPeps2: state.nombreFamiliarPeps2,
          parentescoFamiliarPeps2Codigo: state.parentescoFamiliarPeps2Codigo,
          cargoFamiliarPeps2: state.cargoFamiliarPeps2,
          nombreEntidadPeps2: state.nombreEntidadPeps2,
          periodoPeps2: state.periodoPeps2,
          paisPeps2: state.paisPeps2,
          esFamiliarEmpleado: state.esFamiliarEmpleado,
          nombreFamiliar: state.nombreFamiliar,
          cedulaFamiliar: state.cedulaFamiliar,
          tipoDocumentoCodigo: state.tipoDocumentoCodigo,
          tipoPersonaCodigo: state.tipoPersonaCodigo,
          plazoSolicitud: state.plazoSolicitud,
          fechaPrimerPagoSolicitud:
              DateTime.parse(state.fechaPrimerPagoSolicitud),
          isOffline: false,
          codigoUsa: state.codigoUsa,
          nombre3: state.nombre3,
          apellido3: state.apellido3,
          rtn: state.rtn,
          telefonoNegocio: state.telefonoNegocio,
          celularNegocio: state.celularNegocio,
          // actividadDescripcionConyugue: state.actividaddesc,
          exeperiencia: int.tryParse(state.experiencia) ?? 0,
          puestoNegocio: state.puestoNegocio,
          actividadEconomicaCnbs1Codigo: state.actividadEconomicaCiuu1Codigo,
          actividadEconomicaCnbs2Codigo: state.actividadEconomicaCiuu2Codigo,
          actividaEconomicaDescipcion1: state.actividadEconomicaDescripcion1,
          actividaEconomicaDescipcion2: state.actividadEconomicaDescripcion2,
          actividaEconomicaDescipcion3: state.actividadEconomicaDescripcion3,
          ejerceApnfd: state.ejerceApnfd,
          esApnfd: state.esApnfd,
          nacinalidadCodigo: state.nacionalidad,
          nacinalidad2Codigo: state.nacionalidad2Codigo,
          nacinalidad3Codigo: state.nacionalidad3Codigo,
          departamentoDestinoCodigo: state.departamentoDestinoCodigo,
          tipoPersonaCnbsCodigo: state.tipoPersonaCNBSCodigo,
          tipoClienteCodigo: state.tipoClienteCodigo,
          aldeaDestinoCodigo: state.aldeaDestinoCodigo,
          municipioDestinoCodigo: state.municipioDestinoCodigo,
          aldeaNegocioCodigo: state.aldeaNegocioCodigo,
          departamentoNegocioCodigo: state.departamentoNegocioCodigo,
          nivelAproximadoIngresosCodigo: '',
          // documentoConyuge: state.conyu,
          ocupacionCodigo: state.ocupacionCodigo,
          profesionCodigo: state.profesionCodigo,
          aldeaCasaCodigo: state.aldeaCodigo,
          ubicacionCodigo: state.ubicacion,
          medidasConocimientoCodigo: 'NORM',
          caserioCasa: state.caserioCasa,
          caserioNegocio: state.caserioNegocio,
          caserioDestino: state.caserioDestino,
          barrioDestino: state.barrioDestino,
          descripcionDestino: state.descripcionDestino,
          ingresosNetos: state.ingresosNetos,
          nombre2: state.nombre2,
          apellido2: state.apellido2,
          email: state.email,
          nombreCompletoConyugue: state.nombreConyugue,
          tipoDocumentoConyugeCodigo: state.tipoDocumentoConyugeCodigo,
          grupoCodigo: state.grupoCodigo,
          cargoGrupoCodigo: state.cargoGrupoCodigo,
          fechaEmisionCedula: DateTime.tryParse(state.fechaEmisionCedula),
          grupoCicloID: state.grupoCicloId,
          historialCredito: state.historialCredito,
        ),
      );
      emit(state.copyWith(updateStatus: Status.done));
    } on AppException catch (e) {
      emit(state.copyWith(
        updateStatus: Status.error,
        errorMsg: e.optionalMsg,
      ));
    } catch (e) {
      emit(state.copyWith(
        updateStatus: Status.error,
        errorMsg: e.toString(),
      ));
    }
  }
}
