import 'package:bloc/bloc.dart';
import 'package:core_financiero_app/src/datasource/solicitudes/nueva_menor/solicitud_nueva_menor.dart';
import 'package:core_financiero_app/src/domain/repository/solicitudes_credito/solicitudes_credito_repository.dart';
import 'package:core_financiero_app/src/presentation/bloc/branch_team/branchteam_cubit.dart';
import 'package:equatable/equatable.dart';

part 'solicitud_nueva_menor_state.dart';

class SolicitudNuevaMenorCubit extends Cubit<SolicitudNuevaMenorState> {
  final SolicitudesCreditoRepository repository;
  SolicitudNuevaMenorCubit(this.repository)
      : super(SolicitudNuevaMenorInitial());

  Future<void> createSolicitudNuevaMenor() async {
    try {
      final (isOk, msg) = await repository.createSolicitudCreditoNuevaMenor(
          solicitudNuevaMenor: SolicitudNuevaMenor(
        objOrigenSolicitudId: state.objOrigenSolicitudId,
        nombre1: state.nombre1,
        nombre2: state.nombre2,
        apellido1: state.apellido1,
        apellido2: state.apellido2,
        cedula: state.cedula,
        objPaisEmisorCedula: state.objPaisEmisorCedula,
        fechaEmisionCedula: state.fechaEmisionCedula,
        fechaVencimientoCedula: state.fechaVencimientoCedula,
        fechaNacimiento: state.fechaNacimiento,
        telefono: state.telefono,
        celular: state.celular,
        direccionCasa: state.direccionCasa,
        barrioCasa: state.barrioCasa,
        objMunicipioCasaId: state.objMunicipioCasaId,
        objDepartamentoCasaId: state.objDepartamentoCasaId,
        objPaisCasaId: state.objPaisCasaId,
        profesion: state.profesion,
        ocupacion: state.ocupacion,
        nacionalidad: state.nacionalidad,
        objCondicionCasaId: state.objCondicionCasaId,
        anosResidirCasa: state.anosResidirCasa,
        email: state.email,
        monto: state.monto,
        objMonedaId: state.objMonedaId,
        objPropositoId: state.objPropositoId,
        objFrecuenciaId: state.objFrecuenciaId,
        cuota: state.cuota,
        objActividadId: state.objActividadId,
        objActividadId1: state.objActividadId1,
        objActividadId2: state.objActividadId2,
        objSectorId: state.objSectorId,
        nombreNegocio: state.nombreNegocio,
        tiempoFuncionamientoNegocio: state.tiempoFuncionamientoNegocio,
        direccionNegocio: state.direccionNegocio,
        barrioNegocio: state.barrioNegocio,
        objMunicipioNegocioId: state.objMunicipioNegocioId,
        objCondicionNegocioId: state.objCondicionNegocioId,
        horarioTrabajo: state.horarioTrabajo,
        horarioVisita: state.horarioVisita,
        personasACargo: state.personasACargo,
        objEstadoCivilId: state.objEstadoCivilId,
        nombreConyugue: state.nombreConyugue,
        trabajaConyugue: state.trabajaConyugue,
        trabajoConyugue: state.trabajoConyugue,
        direccionTrabajoConyugue: state.direccionTrabajoConyugue,
        telefonoTrabajoConyugue: state.telefonoTrabajoConyugue,
        beneficiarioSeguro: state.beneficiarioSeguro,
        cedulaBeneficiarioSeguro: state.cedulaBeneficiarioSeguro,
        objParentescoBeneficiarioSeguroId:
            state.objParentescoBeneficiarioSeguroId,
        beneficiarioSeguro1: state.beneficiarioSeguro1,
        cedulaBeneficiarioSeguro1: state.cedulaBeneficiarioSeguro1,
        objParentescoBeneficiarioSeguroId1:
            state.objParentescoBeneficiarioSeguroId1,
        objEstadoSolicitudId: state.objEstadoSolicitudId,
        objOficialCreditoId: state.objOficialCreditoId,
        objProductoId: state.objProductoId,
        observacion: state.observacion,
        sucursal: state.sucursal,
        ubicacionLongitud: state.ubicacionLongitud,
        ubicacionLatitud: state.ubicacionLatitud,
        ubicacionGradosLongitud: state.ubicacionGradosLongitud,
        ubicacionGradosLatitud: state.ubicacionGradosLatitud,
        objEscolaridadId: state.objEscolaridadId,
        cantidadHijos: state.cantidadHijos,
        nombrePublico: state.nombrePublico,
        objSexoId: state.objSexoId,
        objPaisNacimientoId: state.objPaisNacimientoId,
        nacionalidadConyugue: state.nacionalidadConyugue,
        database: state.database,
        ubicacion: state.ubicacion,
        espeps: state.espeps,
        nombreDeEntidadPeps: state.nombreDeEntidadPeps,
        paisPeps: state.paisPeps,
        periodoPeps: state.periodoPeps,
        cargoOficialPeps: state.cargoOficialPeps,
        tieneFamiliarPeps: state.tieneFamiliarPeps,
        nombreFamiliarPeps2: state.nombreFamiliarPeps2,
        parentescoFamiliarPeps2: state.parentescoFamiliarPeps2,
        cargoFamiliarPeps2: state.cargoFamiliarPeps2,
        nombreEntidadPeps2: state.nombreEntidadPeps2,
        periodoPeps2: state.periodoPeps2,
        paisPeps2: state.paisPeps2,
        objRubroActividad: state.objRubroActividad,
        objActividadPredominante: state.objActividadPredominante,
        esFamiliarEmpleado: state.esFamiliarEmpleado,
        nombreFamiliar: state.nombreFamiliar,
        cedulaFamiliar: state.cedulaFamiliar,
        objTipoDocumentoId: state.objTipoDocumentoId,
        objRubroActividad2: state.objRubroActividad2,
        objRubroActividad3: state.objRubroActividad3,
        objRubroActividadPredominante: state.objRubroActividadPredominante,
        tipoPersona: state.tipoPersona,
        objTipoPersonaId: state.objTipoPersonaId,
        telefonoBeneficiario: state.telefonoBeneficiario,
        telefonoBeneficiarioSeguro1: state.telefonoBeneficiarioSeguro1,
        plazoSolicitud: state.plazoSolicitud,
        fechaPrimerPagoSolicitud: state.fechaPrimerPagoSolicitud,
      ));
      if (!isOk) {
        return emit(state.copyWith(status: Status.error, errorMsg: msg));
      }
      emit(state.copyWith(status: Status.done));
    } catch (e) {
      emit(state.copyWith(status: Status.error, errorMsg: e.toString()));
    }
  }

  void saveAnswers({
    required String objOrigenSolicitudId,
    required String nombre1,
    required String nombre2,
    required String apellido1,
    required String apellido2,
    required String cedula,
    required String objPaisEmisorCedula,
    required String fechaEmisionCedula,
    required String fechaVencimientoCedula,
    required String fechaNacimiento,
    required String telefono,
    required String celular,
    required String direccionCasa,
    required String barrioCasa,
    required String objMunicipioCasaId,
    required String objDepartamentoCasaId,
    required String objPaisCasaId,
    required String profesion,
    required String ocupacion,
    required String nacionalidad,
    required String objCondicionCasaId,
    required int anosResidirCasa,
    required String email,
    required int monto,
    required String objMonedaId,
    required String objPropositoId,
    required String objFrecuenciaId,
    required int cuota,
    required String objActividadId,
    required String objActividadId1,
    required String objActividadId2,
    required String objSectorId,
    required String nombreNegocio,
    required String tiempoFuncionamientoNegocio,
    required String direccionNegocio,
    required String barrioNegocio,
    required String objMunicipioNegocioId,
    required String objCondicionNegocioId,
    required String horarioTrabajo,
    required String horarioVisita,
    required int personasACargo,
    required String objEstadoCivilId,
    required String nombreConyugue,
    required bool trabajaConyugue,
    required String trabajoConyugue,
    required String direccionTrabajoConyugue,
    required String telefonoTrabajoConyugue,
    required String beneficiarioSeguro,
    required String cedulaBeneficiarioSeguro,
    required String objParentescoBeneficiarioSeguroId,
    required String beneficiarioSeguro1,
    required String cedulaBeneficiarioSeguro1,
    required String objParentescoBeneficiarioSeguroId1,
    required String objEstadoSolicitudId,
    required String objOficialCreditoId,
    required String objProductoId,
    required String observacion,
    required String sucursal,
    required String ubicacionLongitud,
    required String ubicacionLatitud,
    required String ubicacionGradosLongitud,
    required String ubicacionGradosLatitud,
    required String objEscolaridadId,
    required int cantidadHijos,
    required String nombrePublico,
    required String objSexoId,
    required String objPaisNacimientoId,
    required String nacionalidadConyugue,
    required String database,
    required String ubicacion,
    required bool espeps,
    required String nombreDeEntidadPeps,
    required String paisPeps,
    required String periodoPeps,
    required String cargoOficialPeps,
    required bool tieneFamiliarPeps,
    required String nombreFamiliarPeps2,
    required String parentescoFamiliarPeps2,
    required String cargoFamiliarPeps2,
    required String nombreEntidadPeps2,
    required String periodoPeps2,
    required String paisPeps2,
    required String objRubroActividad,
    required String objActividadPredominante,
    required bool esFamiliarEmpleado,
    required String nombreFamiliar,
    required String cedulaFamiliar,
    required String objTipoDocumentoId,
    required String objRubroActividad2,
    required String objRubroActividad3,
    required String objRubroActividadPredominante,
    required int tipoPersona,
    required String objTipoPersonaId,
    required String telefonoBeneficiario,
    required String telefonoBeneficiarioSeguro1,
    required int plazoSolicitud,
    required String fechaPrimerPagoSolicitud,
  }) {
    emit(
      state.copyWith(
        objOrigenSolicitudId: objOrigenSolicitudId,
        nombre1: nombre1,
        nombre2: nombre2,
        apellido1: apellido1,
        apellido2: apellido2,
        cedula: cedula,
        objPaisEmisorCedula: objPaisEmisorCedula,
        fechaEmisionCedula: fechaEmisionCedula,
        fechaVencimientoCedula: fechaVencimientoCedula,
        fechaNacimiento: fechaNacimiento,
        telefono: telefono,
        celular: celular,
        direccionCasa: direccionCasa,
        barrioCasa: barrioCasa,
        objMunicipioCasaId: objMunicipioCasaId,
        objDepartamentoCasaId: objDepartamentoCasaId,
        objPaisCasaId: objPaisCasaId,
        profesion: profesion,
        ocupacion: ocupacion,
        nacionalidad: nacionalidad,
        objCondicionCasaId: objCondicionCasaId,
        anosResidirCasa: anosResidirCasa,
        email: email,
        monto: monto,
        objMonedaId: objMonedaId,
        objPropositoId: objPropositoId,
        objFrecuenciaId: objFrecuenciaId,
        cuota: cuota,
        objActividadId: objActividadId,
        objActividadId1: objActividadId1,
        objActividadId2: objActividadId2,
        objSectorId: objSectorId,
        nombreNegocio: nombreNegocio,
        tiempoFuncionamientoNegocio: tiempoFuncionamientoNegocio,
        direccionNegocio: direccionNegocio,
        barrioNegocio: barrioNegocio,
        objMunicipioNegocioId: objMunicipioNegocioId,
        objCondicionNegocioId: objCondicionNegocioId,
        horarioTrabajo: horarioTrabajo,
        horarioVisita: horarioVisita,
        personasACargo: personasACargo,
        objEstadoCivilId: objEstadoCivilId,
        nombreConyugue: nombreConyugue,
        trabajaConyugue: trabajaConyugue,
        trabajoConyugue: trabajoConyugue,
        direccionTrabajoConyugue: direccionTrabajoConyugue,
        telefonoTrabajoConyugue: telefonoTrabajoConyugue,
        beneficiarioSeguro: beneficiarioSeguro,
        cedulaBeneficiarioSeguro: cedulaBeneficiarioSeguro,
        objParentescoBeneficiarioSeguroId: objParentescoBeneficiarioSeguroId,
        beneficiarioSeguro1: beneficiarioSeguro1,
        cedulaBeneficiarioSeguro1: cedulaBeneficiarioSeguro1,
        objParentescoBeneficiarioSeguroId1: objParentescoBeneficiarioSeguroId1,
        objEstadoSolicitudId: objEstadoSolicitudId,
        objOficialCreditoId: objOficialCreditoId,
        objProductoId: objProductoId,
        observacion: observacion,
        sucursal: sucursal,
        ubicacionLongitud: ubicacionLongitud,
        ubicacionLatitud: ubicacionLatitud,
        ubicacionGradosLongitud: ubicacionGradosLongitud,
        ubicacionGradosLatitud: ubicacionGradosLatitud,
        objEscolaridadId: objEscolaridadId,
        cantidadHijos: cantidadHijos,
        nombrePublico: nombrePublico,
        objSexoId: objSexoId,
        objPaisNacimientoId: objPaisNacimientoId,
        nacionalidadConyugue: nacionalidadConyugue,
        database: database,
        ubicacion: ubicacion,
        espeps: espeps,
        nombreDeEntidadPeps: nombreDeEntidadPeps,
        paisPeps: paisPeps,
        periodoPeps: periodoPeps,
        cargoOficialPeps: cargoOficialPeps,
        tieneFamiliarPeps: tieneFamiliarPeps,
        nombreFamiliarPeps2: nombreFamiliarPeps2,
        parentescoFamiliarPeps2: parentescoFamiliarPeps2,
        cargoFamiliarPeps2: cargoFamiliarPeps2,
        nombreEntidadPeps2: nombreEntidadPeps2,
        periodoPeps2: periodoPeps2,
        paisPeps2: paisPeps2,
        objRubroActividad: objRubroActividad,
        objActividadPredominante: objActividadPredominante,
        esFamiliarEmpleado: esFamiliarEmpleado,
        nombreFamiliar: nombreFamiliar,
        cedulaFamiliar: cedulaFamiliar,
        objTipoDocumentoId: objTipoDocumentoId,
        objRubroActividad2: objRubroActividad2,
        objRubroActividad3: objRubroActividad3,
        objRubroActividadPredominante: objRubroActividadPredominante,
        tipoPersona: tipoPersona,
        objTipoPersonaId: objTipoPersonaId,
        telefonoBeneficiario: telefonoBeneficiario,
        telefonoBeneficiarioSeguro1: telefonoBeneficiarioSeguro1,
        plazoSolicitud: plazoSolicitud,
        fechaPrimerPagoSolicitud: fechaPrimerPagoSolicitud,
      ),
    );
  }
}
